---
language: node_js
node_js:
  - "6"

sudo: required

addons:
  chrome: stable

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false

install:
  - npm install

script:
  - npm test
